/// Flutter icons MyFonts
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFonts
///      fonts:
///       - asset: fonts/MyFonts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFonts {
  MyFonts._();

  static const _kFontFam = 'MyFonts';

  static const IconData linkedin = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xe802, fontFamily: _kFontFam);
}
